2022-05-22 21:47:18.933245: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-05-22 21:47:18.933300: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: gpu014
2022-05-22 21:47:18.933310: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: gpu014
2022-05-22 21:47:18.933433: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 510.47.3
2022-05-22 21:47:18.933459: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 470.82.1
2022-05-22 21:47:18.933467: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:313] kernel version 470.82.1 does not match DSO version 510.47.3 -- cannot find working devices in this configuration
2022-05-22 21:47:18.937775: I tensorflow/core/platform/cpu_feature_guard.cc:152] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Some layers from the model checkpoint at ./bert-base-german-cased were not used when initializing TFBertModel: ['mlm___cls', 'nsp___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at ./bert-base-german-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.
Traceback (most recent call last):
  File "nmt_model_test.py", line 231, in <module>
    out = model((i, dec_inp)).numpy()[0].decode('utf-8')
AttributeError: 'numpy.ndarray' object has no attribute 'decode'
